### PR TITLE
Add total utilization which should allow deducing interference 

### PR DESCRIPTION
**Pull request by badrpc**
UniFi controller UI displays interference as (total - tx - rx)

### CODE REVIEW

**Comment by davidnewhall** [comment]
Can't you just sum rx and tx in Grafana to get the total?

**Comment by badrpc** [comment]
> Can't you just sum rx and tx in Grafana to get the total?

That's not the same. Total as reported by controller includes interference from other stations on the same channel. I'm regularly seeing Total > Rx + Tx.

**Comment by badrpc** [comment]
This is how controller shows it and how sometimes total can be noticeably greater than a sum of Tx and Rx.
Notice how in Ch. Util. (Busy/Rx/Tx) 5 (busy or total) != 2 (rx) + 2 (tx).

Screenshot from 2020-10-26 20-17-03
Screenshot from 2020-10-26 20-17-15
Screenshot from 2020-10-26 20-17-57

**Comment by davidnewhall** [comment]
If you look at the raw numbers in the API.. is it the same thing?

**Comment by badrpc** [comment]
> If you look at the raw numbers in the API.. is it the same thing?

I checked what controller UI gets as JSON (using network explorer in my browser) and found variables there. I then found them in unifi library, added to promunifi and built exporter I'm currently using. Numbers I'm seeing in UI match what I see in the exporter. For example the two controller UI screenshots above correspond to timestamps 2020-10-26 20:17:03 and 20:17:15 (local time) and here's what was exported at that time:

cu_total_20201026201715

This was convincing enough for me but please let me know if you'd me to check something else.

**Comment by patagonaa** [comment]
Please add this, these metrics can differ from just RX+TX a lot when there are other WiFi networks around.
This is a really important metric for deciding which WiFi channels to use and which ones to avoid!

Example with a lot of interference on a particular WiFi channel (self = RX + TX; total = total):
image

**Comment by davidnewhall** [comment]
I haven't messed with poller in a few months. I'll make sure this is in the next release.

**Pull request merged**
